# Generated by Django 3.2.9 on 2021-11-29 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_contato_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_agendauser_contatos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgendaUser',
            new_name='UserContatos',
        ),
    ]
