# Generated by Django 3.2.9 on 2021-11-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211129_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontatos',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='UserContatos',
        ),
    ]
