# Generated by Django 3.2.9 on 2021-11-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_data_criacao_contato_data de criação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Data de criação',
            new_name='data_criacao',
        ),
    ]
