# Generated by Django 3.2.9 on 2021-11-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211129_1844'),
        ('contatos', '0005_contato_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
